version: '3'

tasks:
    default:
        desc: List all available tasks
        cmds:
            - task --list-all
    blockchain:
        desc: Start solana-test-validator and deploy contracts
        cmds:
            - |
                echo "Deploying contracts..."
                ./scripts/setup_blockchain.sh
        silent: false

    frontend:
        desc: Starts the Next.js frontend application as well as the packages
        cmds:
            - pnpm i && pnpm dev
        silent: true

    backend:
        desc: Starts the Go backend application
        cmds:
            - cd apps/backend && task run
        silent: true
